[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.env]
NODE_ENV = "production" 